// =============================================================================
// STEMKit Journal Abbreviator | dictionary
// =============================================================================
// This file is the ONLY place you need to touch to add or fix a journal.
//
// Each entry is a pair:  ["Full Journal Name", "Standard Abbreviation"]
//
// You do NOT need to add variants, the engine automatically tolerates:
//   * a leading "The"                 (The Journal of Chemical Physics)
//   * "&" vs "and"                    (Energy & Environmental Science)
//   * missing/extra colons and commas (Journal of Physics Condensed Matter)
//   * hyphen / en-dash / em-dash      (Chemistry - A European Journal)
//   * any capitalisation and any run of whitespace (incl. line-wrapped titles)
//
// Longest titles always win over shorter ones, so "Nature Chemistry" is safe
// next to "Nature". Entries where the "abbreviation" equals the full name
// (Nature, Science, Small, ...) are kept for documentation but never alter or
// highlight text, so common English words are never touched.
//
// Sources: CASSI (cassi.cas.org) and the ISSN LTWA (ISO 4). Hand-checked, but
// corrections welcome.
// =============================================================================

window.STEMKIT_JOURNALS = [

    // ── ACS ────────────────────────────────────────────────────────────────
    ["Journal of the American Chemical Society", "J. Am. Chem. Soc."],
    ["JACS Au", "JACS Au"],
    ["Journal of Physical Chemistry A", "J. Phys. Chem. A"],
    ["Journal of Physical Chemistry B", "J. Phys. Chem. B"],
    ["Journal of Physical Chemistry C", "J. Phys. Chem. C"],
    ["Journal of Physical Chemistry Letters", "J. Phys. Chem. Lett."],
    ["Journal of Chemical Theory and Computation", "J. Chem. Theory Comput."],
    ["Journal of Chemical Information and Modeling", "J. Chem. Inf. Model."],
    ["Journal of Chemical Education", "J. Chem. Educ."],
    ["Journal of Chemical & Engineering Data", "J. Chem. Eng. Data"],
    ["Journal of Organic Chemistry", "J. Org. Chem."],
    ["Organic Letters", "Org. Lett."],
    ["Organometallics", "Organometallics"],
    ["Inorganic Chemistry", "Inorg. Chem."],
    ["Analytical Chemistry", "Anal. Chem."],
    ["Accounts of Chemical Research", "Acc. Chem. Res."],
    ["Chemical Reviews", "Chem. Rev."],
    ["ACS Nano", "ACS Nano"],
    ["ACS Catalysis", "ACS Catal."],
    ["ACS Energy Letters", "ACS Energy Lett."],
    ["ACS Central Science", "ACS Cent. Sci."],
    ["ACS Omega", "ACS Omega"],
    ["ACS Photonics", "ACS Photonics"],
    ["ACS Sensors", "ACS Sens."],
    ["ACS Macro Letters", "ACS Macro Lett."],
    ["ACS Applied Materials & Interfaces", "ACS Appl. Mater. Interfaces"],
    ["ACS Applied Energy Materials", "ACS Appl. Energy Mater."],
    ["ACS Applied Nano Materials", "ACS Appl. Nano Mater."],
    ["ACS Sustainable Chemistry & Engineering", "ACS Sustainable Chem. Eng."],
    ["Nano Letters", "Nano Lett."],
    ["Macromolecules", "Macromolecules"],
    ["Biomacromolecules", "Biomacromolecules"],
    ["Langmuir", "Langmuir"],
    ["Chemistry of Materials", "Chem. Mater."],
    ["Crystal Growth & Design", "Cryst. Growth Des."],
    ["Industrial & Engineering Chemistry Research", "Ind. Eng. Chem. Res."],
    ["Energy & Fuels", "Energy Fuels"],
    ["Journal of Agricultural and Food Chemistry", "J. Agric. Food Chem."],
    ["Environmental Science & Technology", "Environ. Sci. Technol."],
    ["Journal of Medicinal Chemistry", "J. Med. Chem."],
    ["Bioconjugate Chemistry", "Bioconjugate Chem."],

    // ── AIP / APS / IOP (physics) ──────────────────────────────────────────
    ["Journal of Chemical Physics", "J. Chem. Phys."],
    ["Physical Review Letters", "Phys. Rev. Lett."],
    ["Physical Review A", "Phys. Rev. A"],
    ["Physical Review B", "Phys. Rev. B"],
    ["Physical Review C", "Phys. Rev. C"],
    ["Physical Review D", "Phys. Rev. D"],
    ["Physical Review E", "Phys. Rev. E"],
    ["Physical Review X", "Phys. Rev. X"],
    ["Physical Review Materials", "Phys. Rev. Mater."],
    ["Physical Review Applied", "Phys. Rev. Appl."],
    ["Physical Review Research", "Phys. Rev. Res."],
    ["Reviews of Modern Physics", "Rev. Mod. Phys."],
    ["Applied Physics Letters", "Appl. Phys. Lett."],
    ["Journal of Applied Physics", "J. Appl. Phys."],
    ["AIP Advances", "AIP Adv."],
    ["Review of Scientific Instruments", "Rev. Sci. Instrum."],
    ["Physics of Fluids", "Phys. Fluids"],
    ["Journal of Physics: Condensed Matter", "J. Phys.: Condens. Matter"],
    ["Journal of Physics D: Applied Physics", "J. Phys. D: Appl. Phys."],
    ["New Journal of Physics", "New J. Phys."],
    ["Reports on Progress in Physics", "Rep. Prog. Phys."],
    ["Nanotechnology", "Nanotechnology"],
    ["2D Materials", "2D Mater."],
    ["Superconductor Science and Technology", "Supercond. Sci. Technol."],
    ["Journal of Vacuum Science & Technology A", "J. Vac. Sci. Technol., A"],
    ["European Physical Journal B", "Eur. Phys. J. B"],
    ["European Physical Journal C", "Eur. Phys. J. C"],
    ["Journal of High Energy Physics", "J. High Energy Phys."],
    ["Annual Review of Physical Chemistry", "Annu. Rev. Phys. Chem."],
    ["Molecular Physics", "Mol. Phys."],

    // ── RSC ────────────────────────────────────────────────────────────────
    ["Chemical Communications", "Chem. Commun."],
    ["Chemical Society Reviews", "Chem. Soc. Rev."],
    ["Chemical Science", "Chem. Sci."],
    ["Physical Chemistry Chemical Physics", "Phys. Chem. Chem. Phys."],
    ["Energy & Environmental Science", "Energy Environ. Sci."],
    ["Green Chemistry", "Green Chem."],
    ["Journal of Materials Chemistry A", "J. Mater. Chem. A"],
    ["Journal of Materials Chemistry B", "J. Mater. Chem. B"],
    ["Journal of Materials Chemistry C", "J. Mater. Chem. C"],
    ["Dalton Transactions", "Dalton Trans."],
    ["Nanoscale", "Nanoscale"],
    ["Nanoscale Horizons", "Nanoscale Horiz."],
    ["Materials Horizons", "Mater. Horiz."],
    ["Soft Matter", "Soft Matter"],
    ["RSC Advances", "RSC Adv."],
    ["CrystEngComm", "CrystEngComm"],
    ["New Journal of Chemistry", "New J. Chem."],
    ["Lab on a Chip", "Lab Chip"],
    ["Faraday Discussions", "Faraday Discuss."],
    ["Organic & Biomolecular Chemistry", "Org. Biomol. Chem."],
    ["Catalysis Science & Technology", "Catal. Sci. Technol."],
    ["Journal of Analytical Atomic Spectrometry", "J. Anal. At. Spectrom."],

    // ── Wiley ──────────────────────────────────────────────────────────────
    ["Angewandte Chemie International Edition", "Angew. Chem., Int. Ed."],
    ["Angewandte Chemie", "Angew. Chem."],
    ["Advanced Materials", "Adv. Mater."],
    ["Advanced Functional Materials", "Adv. Funct. Mater."],
    ["Advanced Energy Materials", "Adv. Energy Mater."],
    ["Advanced Optical Materials", "Adv. Opt. Mater."],
    ["Advanced Electronic Materials", "Adv. Electron. Mater."],
    ["Advanced Materials Interfaces", "Adv. Mater. Interfaces"],
    ["Advanced Science", "Adv. Sci."],
    ["Small", "Small"],
    ["Chemistry - A European Journal", "Chem. - Eur. J."],
    ["European Journal of Organic Chemistry", "Eur. J. Org. Chem."],
    ["European Journal of Inorganic Chemistry", "Eur. J. Inorg. Chem."],
    ["Macromolecular Rapid Communications", "Macromol. Rapid Commun."],
    ["Journal of Computational Chemistry", "J. Comput. Chem."],
    ["Journal of Raman Spectroscopy", "J. Raman Spectrosc."],

    // ── Nature portfolio / Science / PNAS ──────────────────────────────────
    ["Nature", "Nature"],
    ["Nature Chemistry", "Nat. Chem."],
    ["Nature Materials", "Nat. Mater."],
    ["Nature Physics", "Nat. Phys."],
    ["Nature Nanotechnology", "Nat. Nanotechnol."],
    ["Nature Communications", "Nat. Commun."],
    ["Nature Energy", "Nat. Energy"],
    ["Nature Catalysis", "Nat. Catal."],
    ["Nature Photonics", "Nat. Photonics"],
    ["Nature Electronics", "Nat. Electron."],
    ["Nature Synthesis", "Nat. Synth."],
    ["Nature Methods", "Nat. Methods"],
    ["Nature Biotechnology", "Nat. Biotechnol."],
    ["Nature Reviews Chemistry", "Nat. Rev. Chem."],
    ["Nature Reviews Materials", "Nat. Rev. Mater."],
    ["Communications Chemistry", "Commun. Chem."],
    ["Communications Physics", "Commun. Phys."],
    ["Communications Materials", "Commun. Mater."],
    ["npj Computational Materials", "npj Comput. Mater."],
    ["Scientific Reports", "Sci. Rep."],
    ["Science", "Science"],
    ["Science Advances", "Sci. Adv."],
    ["Proceedings of the National Academy of Sciences of the United States of America", "Proc. Natl. Acad. Sci. U.S.A."],
    ["Proceedings of the National Academy of Sciences", "Proc. Natl. Acad. Sci. U.S.A."],

    // ── Cell Press ─────────────────────────────────────────────────────────
    ["Joule", "Joule"],
    ["Chem Catalysis", "Chem Catal."],
    ["Cell Reports Physical Science", "Cell Rep. Phys. Sci."],
    ["Trends in Chemistry", "Trends Chem."],

    // ── Elsevier ───────────────────────────────────────────────────────────
    ["Tetrahedron Letters", "Tetrahedron Lett."],
    ["Chemical Physics Letters", "Chem. Phys. Lett."],
    ["Chemical Physics", "Chem. Phys."],
    ["Chemical Engineering Journal", "Chem. Eng. J."],
    ["Chemical Engineering Science", "Chem. Eng. Sci."],
    ["Journal of Catalysis", "J. Catal."],
    ["Applied Catalysis A: General", "Appl. Catal., A"],
    ["Applied Catalysis B: Environmental", "Appl. Catal., B"],
    ["Journal of Power Sources", "J. Power Sources"],
    ["Electrochimica Acta", "Electrochim. Acta"],
    ["Electrochemistry Communications", "Electrochem. Commun."],
    ["Journal of Electroanalytical Chemistry", "J. Electroanal. Chem."],
    ["Acta Materialia", "Acta Mater."],
    ["Scripta Materialia", "Scr. Mater."],
    ["Journal of Alloys and Compounds", "J. Alloys Compd."],
    ["Journal of Solid State Chemistry", "J. Solid State Chem."],
    ["Journal of Crystal Growth", "J. Cryst. Growth"],
    ["Journal of Physics and Chemistry of Solids", "J. Phys. Chem. Solids"],
    ["Surface Science", "Surf. Sci."],
    ["Applied Surface Science", "Appl. Surf. Sci."],
    ["Journal of Colloid and Interface Science", "J. Colloid Interface Sci."],
    ["Colloids and Surfaces A: Physicochemical and Engineering Aspects", "Colloids Surf., A"],
    ["Journal of Molecular Structure", "J. Mol. Struct."],
    ["Journal of Molecular Liquids", "J. Mol. Liq."],
    ["Journal of Magnetic Resonance", "J. Magn. Reson."],
    ["Journal of Magnetism and Magnetic Materials", "J. Magn. Magn. Mater."],
    ["Journal of Luminescence", "J. Lumin."],
    ["Journal of Membrane Science", "J. Membr. Sci."],
    ["Journal of Nuclear Materials", "J. Nucl. Mater."],
    ["Journal of Hazardous Materials", "J. Hazard. Mater."],
    ["Journal of Chromatography A", "J. Chromatogr. A"],
    ["Analytica Chimica Acta", "Anal. Chim. Acta"],
    ["Spectrochimica Acta Part A: Molecular and Biomolecular Spectroscopy", "Spectrochim. Acta, Part A"],
    ["Corrosion Science", "Corros. Sci."],
    ["Computational Materials Science", "Comput. Mater. Sci."],
    ["Journal of Computational Physics", "J. Comput. Phys."],
    ["Progress in Materials Science", "Prog. Mater. Sci."],
    ["Materials Today", "Mater. Today"],
    ["International Journal of Hydrogen Energy", "Int. J. Hydrogen Energy"],
    ["International Journal of Heat and Mass Transfer", "Int. J. Heat Mass Transfer"],
    ["Solar Energy Materials and Solar Cells", "Sol. Energy Mater. Sol. Cells"],
    ["Sensors and Actuators B: Chemical", "Sens. Actuators, B"],
    ["Fluid Phase Equilibria", "Fluid Phase Equilib."],
    ["Water Research", "Water Res."],
    ["Nuclear Instruments and Methods in Physics Research Section A", "Nucl. Instrum. Methods Phys. Res., Sect. A"],

    // ── Other publishers ───────────────────────────────────────────────────
    ["Journal of the Electrochemical Society", "J. Electrochem. Soc."],
    ["Journal of Applied Crystallography", "J. Appl. Crystallogr."],
    ["Journal of Fluid Mechanics", "J. Fluid Mech."],
    ["AIChE Journal", "AIChE J."],
    ["Optics Express", "Opt. Express"],
    ["Optics Letters", "Opt. Lett."],
    ["Applied Optics", "Appl. Opt."],
    ["Journal of the Optical Society of America B", "J. Opt. Soc. Am. B"],
    ["Beilstein Journal of Organic Chemistry", "Beilstein J. Org. Chem."],
    ["Journal of Cheminformatics", "J. Cheminf."],
    ["Journal of Molecular Modeling", "J. Mol. Model."],
    ["Molecular Simulation", "Mol. Simul."],
    ["Atmospheric Chemistry and Physics", "Atmos. Chem. Phys."],
    ["Geochimica et Cosmochimica Acta", "Geochim. Cosmochim. Acta"],
    ["Astrophysical Journal", "Astrophys. J."],
    ["Monthly Notices of the Royal Astronomical Society", "Mon. Not. R. Astron. Soc."],
    ["Astronomy & Astrophysics", "Astron. Astrophys."],
    ["Microscopy and Microanalysis", "Microsc. Microanal."]
];
